# Generated by Django 4.1 on 2023-01-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("couoh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_ID", models.CharField(max_length=255)),
                ("star_score", models.FloatField()),
                ("review_content", models.TextField()),
                ("help_count", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="couoh.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Couoh",
        ),
        migrations.AddField(
            model_name="product",
            name="site",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="couoh.site"
            ),
        ),
    ]
