# Generated by Django 4.1 on 2023-01-13 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("couoh", "0002_product_reviewdata_site_delete_couoh_product_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coucou",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "review_title",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "최소 세 글자 이상이어야 합니다."
                            )
                        ],
                        verbose_name="제목",
                    ),
                ),
                (
                    "review_content",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(10, "최소 10글자")
                        ],
                        verbose_name="내용",
                    ),
                ),
                ("site_name", models.CharField(max_length=255)),
                ("star_score", models.CharField(max_length=255)),
                ("help_count", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("rank", models.CharField(max_length=255)),
                ("category_name", models.CharField(max_length=255)),
                ("customer_ID", models.CharField(max_length=255)),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ohoh",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "review_title",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "최소 세 글자 이상이어야 합니다."
                            )
                        ],
                        verbose_name="제목",
                    ),
                ),
                (
                    "review_content",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(10, "최소 10글자")
                        ],
                        verbose_name="내용",
                    ),
                ),
                ("site_name", models.CharField(max_length=255)),
                ("star_score", models.CharField(max_length=255)),
                ("help_count", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("rank", models.CharField(max_length=255)),
                ("category_name", models.CharField(max_length=255)),
                ("customer_ID", models.CharField(max_length=255)),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
